language: java
jdk:
 - oraclejdk8
deploy:
   provider: heroku
   api_key:
      secure: "qtHY7ibU+eJHsRlSTDq2oLluq45eR9Srdz2vK9azaPdA46NYUcV4UzO08oBrKVvoXf3saQsbV2Amcy6rnbUMQHucGMc+Oo+7/F5YXmqmgcn6+MER1N1vh0KW3QdRcwRyFc5iKMr7fGjWwcewCtJlJ+HU2INN3AB+IrLa1rCf6+eK9z7rqzlIOQtZdY0kGioA0ZngW2T6wfbsalTR6LUulA9LN9i/h7XUqds9FqG4O+6oVZSMgdUVCdDR+QqD8tXsGY5T1zkBOjtEQix6pML5UsczBjfWvnuCEfe5JIBCKb9WQUeMQ1F9VoWLCvBLzhAN6pIcCX9nny5BDIJNOmkHLu8XNDBWNxlJ2q71KOf9+nI3wQtDuJyO3s7jfzK/tT27jbJTwXU7wIY3HLvaAiZpFSuKDfJAWd5GLfKe30/UYN4Wrd3oSKSDi7QIMKI2G1ksin8IKuEPX83L7QQ4MVf1rFx5pM6gSuU8t9uEhv7j7i84+Vp2M+XWDHBPdILUCT50m1lMNb12Q/ufKaXo0EYlOtvouAZ5eMbtzx3XPcn6OH8HIkYlOEWKfFM1dVqCNl1MDPAHrZll3RjEzB48S4YlbPMBZ83LtJtPDXd0f/FJjrvtfLxKRXq6PvYDxT/Jj8cjK0bruU+G2dYAaijyttW/VPM/3jhmA1rmIK0NR3DdtNw="

   app: calm-plains-85377
