language: java
jdk:
 - oraclejdk8
deploy:
   provider: heroku
   api_key:
      secure: "6W8C2juDGgy3Usmi/PidNnKyM5f9GN48o7XjEgo8VVAlM/ggC948RT13D8r2tRZzkEwGaziX9qo6lZu/SXmgAfgJlg1y8d27qh9vjuMin7YwtaXrvU2e6xYyvJ6PB6wa1prvrVvqmoX7A0pJwp4lGEE6zQFg7xG+d4I2WiYRvqvUjexBUdcoL4Q2FWh4lhVTbj6iEqh0R60ffZ9/cJqRDvCahs7W08TJxpLSqklG/BGMwrtuLFIrOQuDPC9VgXiSexGupsDc8VAO9aTvdj0bkfaRvNRhwf+eu99jHiRP/88tLg8ApH3/a7Q5Egd3OyFvRmVqIl7mYAx3UusGl01KLH6iVD2Sb9ponCAIYkGUI+odC5kyU22Js9vuitZt9YgIcqm2KKO6J2HL7zw1ZZuV4D5JdueR50kTJSw1SxJZBNjSKzqV4PQu1o+RBtkwGx8paM8j93jC2VpROAVslljUOJcVsmw+u0dyzEhIKefT9k+zYFNsS1bDNjRDJ+8zbSD6SLkyx1sObQuSK2FuUbkPIrIzvCbbGLF+yi7NdUMopqln5ert4ajMcenYmTFVYdgBGOMzhwE7lRKR8s8h54Kc0dmt70I3jScKHJQ/l6ZWniRKqA1X04xWobhiQxIoejZa8hGG9AgOalxiM8u4LAeCtSwLLpCfseldOC9U0sXVUFg="
   app: calm-plains-85377
