language: java
jdk:
 - oraclejdk8
deploy:
   provider: heroku
   api_key:
      secure: "RBYnR2Ecb99mPZF8zrAOzxjOpbgh1GpBt+Rsp2ZXsX6d5E6j14lnsweY1Euvk1XLvrIg8Upc0teyODRdjc4lKpRjfH5Z8iUJ/8No9dpyJo9prdsf3k/DFY8AbRHdC2jah3HUpNNi11NQBc97f/o7K4ySLa0xoHutVXNi7zSs3Bg7Jm7rryhbedYWphZraGq9peijCI46LyBw09E8WgnMTJefk0qm2ALaym5rBt82taz5ZxPZoniAyFbUBssdGLsYw/5RGGkAm8PWoo8HpQUcoZeD2p5Tj4EiRdRSiKrQfQcakHO3aO524ZOo7EpvNeVKyJp7YfxncUv3QjCrohvjRHu3JUrhejvp4Jophf6MopFW06LAQ1P2hS6fMOxEgvuC7Y0afIa8wPuVLhMR7JS3YYS8yfEXFEnc6of/80w8GLGHDAjKHCgilmC3CgzRBO8SHJbTO2L6IizozqZk8BMyamSDZpz9TlI959+VjLBbyyJslAxzsmeCiy727CmeCPrt/3eNL7BGV1aIqrkexpGKKPUjfXQ4T0xWF1p1Qrn97CGq/GEhuyZoLSHXKxK1GTOX/kQ8vkmsxpcHpyhlhnmwzwl/eQ962speOxq+wQpHXffXuYD3pVPOAOjoptBTcScpd7AEncLUNA1tqmGx0yC4RVU+sXBDrCowqFtBHjhznBc="      
   app: calm-plains-85377
